//  Copyright © AndreyLysikov
//  SPDX-License-Identifier: Apache-2.0

namespace RemoteGameHub.App;

// Russian for every English text Text.T and the page's [[...]] markers ask for.
// No ' in these: some are placed inside the page script's quoted strings.
internal static class TextRu
{
    internal static readonly IReadOnlyDictionary<string, string> Strings = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        [" · {0} blocks in a row"] = " · блокировок подряд: {0}",
        [" · no stream"] = " · без стрима",
        [" (changed)"] = " (изменена)",
        [", top {0} is:"] = ", первые {0}:",
        ["\"{0}\" closed as soon as it started; the log says why."] = "«{0}»: процесс завершился сразу после запуска; причина в логе.",
        ["\"{0}\" could not be started or closed at once; the log says why."] = "«{0}»: не удалось запустить, или процесс сразу завершился; причина в логе.",
        ["\"{0}\" is running on the host."] = "«{0}» работает на хосте.",
        ["{0} attempts"] = "попыток: {0}",
        ["{0} d {1} h"] = "{0} д {1} ч",
        ["{0} did not start"] = "{0} не запустился",
        ["{0} found — click the right one"] = "найдено: {0} — выберите нужную",
        ["{0} games"] = "Игр: {0}",
        ["{0} h {1} min"] = "{0} ч {1} мин",
        ["{0} h {1} min left"] = "осталось {0} ч {1} мин",
        ["{0} is pairing. Open {1} and type the code it is showing."] = "{0} запрашивает сопряжение. Откройте {1} и введите показанный код.",
        ["{0} is running on the host"] = "{0} работает на хосте",
        ["{0} min"] = "{0} мин",
        ["{0} min left"] = "осталось {0} мин",
        ["{0} v{1} is available"] = "Доступна версия {0} v{1}",
        ["<b>Windows does not sign you in by itself.</b> Your account has a password, so after a restart this host cannot be reached until somebody signs in at the machine."] =
            "<b>Windows не входит в систему автоматически.</b> У вашей учётной записи есть пароль, поэтому после перезагрузки хост недоступен, пока кто-нибудь не войдёт в систему за самим компьютером.",
        ["<span class=live>streaming</span> to {0}"] = "<span class=live>стрим</span> на {0}",
        ["a client is streaming from this machine; stop it first."] = "с этого компьютера уже идёт стрим; сначала остановите его.",
        ["A code is four digits."] = "Код — это четыре цифры.",
        ["A device calling itself <b>{0}</b> wants to pair with this machine."] = "Устройство <b>{0}</b> хочет выполнить сопряжение с этим компьютером.",
        ["A file, a shortcut, or steam://rungameid/…"] = "Файл, ярлык или steam://rungameid/…",
        ["a game is running; quit it first."] = "запущена игра; сначала закройте её.",
        ["a game is running; stop it first."] = "запущена игра; сначала остановите её.",
        ["A game needs a name and something to start."] = "Нужно указать название и что запускать.",
        ["Add a game"] = "Добавить игру",
        ["Always"] = "Всегда",
        ["another client is already streaming from this machine."] = "с этого компьютера уже стримит другой клиент.",
        ["any format — it is fetched and converted here"] = "любой формат — картинка будет скачана и сконвертирована",
        ["Arguments"] = "Аргументы",
        ["As it should appear"] = "Как будет отображаться",
        ["Auto"] = "Авто",
        ["Auto hides it and shows the mouse while a launcher waits for you"] = "«Авто» скрывает её и показывает мышь, пока лаунчер ждёт вас",
        ["Automatic sign-in is on now. This host comes back on its own after a restart."] = "Автоматический вход включён. После перезагрузки хост снова станет доступен сам.",
        ["Automatic sign-in is on. This host will be reachable after a restart."] = "Автоматический вход включён. Хост будет доступен после перезагрузки.",
        ["Autostart"] = "Автозапуск",
        ["banned {0} ip"] = "заблокировано IP: {0}",
        ["by hand"] = "вручную",
        ["Cancel"] = "Отмена",
        ["cancelling…"] = "отмена…",
        ["Check failed"] = "Проверка не удалась",
        ["Checking…"] = "Проверка…",
        ["Controllers are unavailable: no controller bus driver is installed. Everything else works."] =
            "Геймпады недоступны: не установлен драйвер шины контроллеров. Всё остальное работает.",
        ["Cover"] = "Обложка",
        ["Edit"] = "Изменить",
        ["Edit game"] = "Изменить игру",
        ["Enable software mouse cursor"] = "Программный курсор мыши",
        ["Fetch"] = "Скачать",
        ["Fetched."] = "Скачано.",
        ["fetching…"] = "скачивание…",
        ["Find by name"] = "Найти по названию",
        ["folder"] = "папка",
        ["Forget"] = "Забыть",
        ["Forget {0}? It will have to pair again."] = "Забыть {0}? Устройству придётся снова выполнить сопряжение.",
        ["Forgotten."] = "Забыто.",
        ["From this folder"] = "Рабочая папка",
        ["High"] = "Высокое",
        ["It could not be fetched: {0}"] = "Не удалось скачать: {0}",
        ["last seen {0} · paired {1}"] = "был в сети {0} · сопряжено {1}",
        ["Let {0} back in? It is counted from nothing again."] = "Разблокировать {0}? Счётчик попыток начнётся заново.",
        ["Let back in"] = "Разблокировать",
        ["Let back in."] = "Разблокировано.",
        ["Living-room TV, Anna's phone…"] = "Телевизор в гостиной, телефон Ани…",
        ["Log"] = "Лог",
        ["looking…"] = "поиск…",
        ["Lossless"] = "Без потерь",
        ["Low"] = "Низкое",
        ["lower for fast games, higher for quiet ones — a remote client drops one level"] =
            "ниже для динамичных игр, выше для спокойных — у удалённого клиента на уровень ниже",
        ["Medium"] = "Среднее",
        ["Name"] = "Название",
        ["Never"] = "Никогда",
        ["Not started: {0}"] = "Не запущено: {0}",
        ["Nothing arrived."] = "Ничего не получено.",
        ["Nothing is waiting for a code. Press Pair on the client and type the digits it shows then; the ones before are of no use now."] =
            "Никто не ждёт код. Нажмите «Сопряжение» на клиенте и введите цифры, которые он покажет; прежние уже не подойдут.",
        ["Nothing is waiting to pair."] = "Никто не ждёт сопряжения.",
        ["Nothing with a picture was found under \"{0}\". Try the name a store would use."] =
            "По запросу «{0}» картинок не найдено. Попробуйте название, как в магазине.",
        ["Open Windows sign-in settings"] = "Открыть настройки входа Windows",
        ["Opened on the machine's screen. In that window untick \"Users must enter a user name and password to use this computer\", press OK, and type the Windows password into the box Windows shows. This page notices when it is done."] =
            "Открыто на экране компьютера. В этом окне снимите флажок «Требовать ввод имени пользователя и пароля», нажмите ОК и введите пароль Windows в окне, которое покажет Windows. Эта страница заметит, когда всё будет готово.",
        ["optional — added after what it starts with"] = "необязательно — добавляются после запускаемого файла",
        ["optional — many games look for their own files beside it"] = "необязательно — многие игры ищут свои файлы рядом",
        ["Or the address of a picture"] = "Или адрес картинки",
        ["Paired devices"] = "Сопряжённые устройства",
        ["Pairing cancelled."] = "Сопряжение отменено.",
        ["Paste the address of a picture."] = "Вставьте адрес картинки.",
        ["Quality"] = "Качество",
        ["Quit"] = "Выход",
        ["Refresh games"] = "Обновить игры",
        ["Refused addresses"] = "Заблокированные адреса",
        ["Remove"] = "Удалить",
        ["Remove {0} from the list?"] = "Удалить {0} из списка?",
        ["Removed."] = "Удалено.",
        ["Rescan games"] = "Пересканировать игры",
        ["Reset {0} to what was found? Its name, command, folder, cover and settings go back to the defaults."] =
            "Сбросить {0} к найденному? Название, команда, папка, обложка и настройки вернутся к исходным.",
        ["Reset to what was found"] = "Сбросить к найденному",
        ["Reset. The game is being scanned again…"] = "Сброшено. Игра сканируется заново…",
        ["Run without a stream — started on the host, shown as running, stopped with Quit"] =
            "Запуск без стрима — запускается на хосте, отображается как запущенное, останавливается выходом",
        ["Running"] = "Запущено",
        ["Save"] = "Сохранить",
        ["Saved."] = "Сохранено.",
        ["Scanning…"] = "Сканирование…",
        ["Search"] = "Найти",
        ["sending…"] = "отправка…",
        ["Sent. The client should finish pairing in a moment."] = "Отправлено. Клиент сейчас завершит сопряжение.",
        ["Show config"] = "Открыть конфиг",
        ["Show log"] = "Открыть лог",
        ["Show status page"] = "Открыть страницу статуса",
        ["Splash screen when game is starting"] = "Заставка при запуске игры",
        ["Start"] = "Запустить",
        ["Started."] = "Запущено.",
        ["Starting {0}"] = "Запуск {0}",
        ["Starts with"] = "Что запускать",
        ["Stop"] = "Остановить",
        ["Stop {0}?"] = "Остановить {0}?",
        ["Stopped."] = "Остановлено.",
        ["That address is not being refused."] = "Этот адрес не заблокирован.",
        ["that application could not be started."] = "не удалось запустить это приложение.",
        ["That file is not a picture this machine can read."] = "Этот файл не является картинкой, которую можно прочитать.",
        ["That is not an http or https address."] = "Это не http- или https-адрес.",
        ["The address answered {0}."] = "Адрес ответил кодом {0}.",
        ["The address answered with nothing."] = "Адрес вернул пустой ответ.",
        ["The configuration file could not be read:"] = "Не удалось прочитать файл конфигурации:",
        ["The configuration file has a mistake and was not read:"] = "В файле конфигурации ошибка, он не прочитан:",
        ["The four digits it is showing"] = "Четыре цифры, которые оно показывает",
        ["The full reason is in {0}."] = "Подробная причина — в {0}.",
        ["The graphics card's encoder could not be opened; streaming is unavailable. The log has the details."] =
            "Не удалось открыть кодировщик видеокарты; стрим недоступен. Подробности в логе.",
        ["The launch request is missing or malforming a parameter this server needs."] =
            "В запросе на запуск нет нужного параметра или он неверный.",
        ["The name to look for"] = "Что искать",
        ["the program is running on the host; there is no stream to resume."] = "программа запущена на хосте; продолжать нечего, стрима нет.",
        ["The resume request is missing a parameter this server needs."] = "В запросе на продолжение нет нужного параметра.",
        ["The scan is not ready yet."] = "Сканирование ещё не готово.",
        ["The server could not open its ports."] = "Сервер не смог открыть свои порты.",
        ["There is no log file."] = "Файла лога нет.",
        ["There is no such device."] = "Такого устройства нет.",
        ["There is no such game."] = "Такой игры нет.",
        ["there is nothing running to resume."] = "нет ничего запущенного, чтобы продолжить.",
        ["this entry is not a program without a stream."] = "эта запись — не программа без стрима.",
        ["This game was added by hand; there is nothing to reset it to."] = "Эта игра добавлена вручную; сбрасывать её не к чему.",
        ["This is v{0}. Click here to open the download page."] = "Сейчас установлена v{0}. Нажмите, чтобы открыть страницу загрузки.",
        ["This page answers only on the local network."] = "Эта страница доступна только из локальной сети.",
        ["This server cannot start the stream: {0}"] = "Сервер не может начать стрим: {0}",
        ["This server needs administrator rights and does not have them."] = "Серверу нужны права администратора, а их нет.",
        ["This server needs Windows 11 or newer."] = "Серверу нужна Windows 11 или новее.",
        ["This stream cannot be resumed: {0}"] = "Этот стрим нельзя продолжить: {0}",
        ["Type a name to look for."] = "Введите название для поиска.",
        ["under a minute left"] = "осталось меньше минуты",
        ["up {0}"] = "Онлайн {0}",
        ["Up to date"] = "Установлена последняя версия",
        ["Upload"] = "Загрузить",
        ["Uploaded."] = "Загружено.",
        ["uploading…"] = "загрузка…",
        ["v{0} is out"] = "Вышла v{0}",
        ["version {0} is out — download"] = "вышла версия {0} — скачать",
        ["waiting for a client"] = "Нет подключенных клиентов",
        ["What came back is not a picture this machine can read."] = "Полученный файл не является картинкой, которую можно прочитать.",
        ["What to call this device"] = "Как назвать это устройство",
        ["Windows can sign <b>{{account}}</b> in automatically. The password is typed into Windows' own settings window and kept by Windows; this server never sees it. Understand what that means first: anybody who switches the machine on lands on that desktop without a password, and a BitLocker drive with no start-up PIN unlocks on its own with it. Locking the screen right after sign-in keeps the machine shut while this host stays reachable: the lock screen is streamed and unlocked from the client."] =
            "Windows может автоматически входить как <b>{{account}}</b>. Пароль вводится в окне настроек самой Windows и хранится ею; этот сервер его не видит. Сначала оцените последствия: любой, кто включит компьютер, попадёт на рабочий стол без пароля, а диск BitLocker без PIN-кода при загрузке разблокируется сам. Если блокировать экран сразу после входа, компьютер останется закрытым, а хост — доступным: экран блокировки стримится, и разблокировать его можно с клиента.",
        ["Windows' sign-in settings could not be opened; the log says why. At the machine, press Win+R and run netplwiz."] =
            "Не удалось открыть настройки входа Windows; причина в логе. За компьютером нажмите Win+R и выполните netplwiz.",
        ["Your account has a password and Windows does not sign in by itself, so this host cannot be reached after a restart until somebody signs in at the machine. Click here for a way to change that."] =
            "У вашей учётной записи есть пароль, и Windows не входит автоматически, поэтому после перезагрузки хост недоступен, пока кто-нибудь не войдёт за компьютером. Нажмите, чтобы узнать, как это изменить.",
    };
}
